version: "3"
services:
  postgres_drivenops_db:
    image: postgres
    container_name: postgres_drivenops_db
    restart: always
    ports:
      - 4457:5432
    env_file:
      - back-end/.env.test

  node_app:
    container_name: node_app
    build: ./back-end
    ports:
      - 5000:5000
    env_file:
      - back-end/.env.test